name: Sync Upstream Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Upstream tag to sync (e.g., v3.4.8)"
                required: false
                type: string
            force:
                description: "Force sync even if version exists locally"
                required: false
                type: boolean
                default: false
    schedule:
        # Run every day at midnight UTC
        - cron: "0 0 * * *"

permissions:
    contents: write
    packages: write
    checks: write
    pull-requests: write

jobs:
    check-upstream-releases:
        name: Check for New Upstream Releases
        runs-on: ubuntu-latest
        outputs:
            new_version: ${{ steps.compare_versions.outputs.new_version }}
            upstream_version: ${{ steps.get_upstream_version.outputs.version }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get Upstream Version
              id: get_upstream_version
              run: |
                  # Use provided tag if available, stripping 'v' prefix if present
                  if [ -n "${{ github.event.inputs.tag }}" ]; then
                    VERSION="${{ github.event.inputs.tag }}"
                    VERSION="${VERSION#v}"
                    echo "Using provided version: $VERSION"
                  else
                    # Get version from upstream main branch package.json
                    VERSION=$(curl -s https://raw.githubusercontent.com/cline/cline/main/package.json | jq -r '.version')
                    if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
                      echo "Failed to get version from upstream package.json"
                      exit 1
                    fi
                    echo "Found upstream version: $VERSION"
                  fi
                  
                  echo "version=$VERSION" >> $GITHUB_OUTPUT

            - name: Check Local Version Status
              id: compare_versions
              run: |
                  UPSTREAM_VERSION="${{ steps.get_upstream_version.outputs.version }}"
                  FORCE="${{ github.event.inputs.force }}"
                  
                  # Check if we already have this version in a branch or tag
                  if git show-ref --verify --quiet "refs/tags/v${UPSTREAM_VERSION}" || \
                     git show-ref --verify --quiet "refs/heads/sync-upstream-v${UPSTREAM_VERSION}" || \
                     git show-ref --verify --quiet "refs/remotes/origin/sync-upstream-v${UPSTREAM_VERSION}"; then
                    
                    if [ "$FORCE" = "true" ]; then
                      echo "Version ${UPSTREAM_VERSION} exists locally, but force flag is set"
                      echo "new_version=true" >> $GITHUB_OUTPUT
                    else
                      echo "Version ${UPSTREAM_VERSION} already exists locally and force flag is not set"
                      echo "new_version=false" >> $GITHUB_OUTPUT
                    fi
                  else
                    echo "Version ${UPSTREAM_VERSION} does not exist locally"
                    echo "new_version=true" >> $GITHUB_OUTPUT
                  fi

    sync-upstream-release:
        name: Sync Upstream Release
        needs: check-upstream-releases
        if: needs.check-upstream-releases.outputs.new_version == 'true'
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.commit.outputs.branch }}
            version: ${{ needs.check-upstream-releases.outputs.upstream_version }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.15.1

            - name: Configure Git
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: Add Upstream Remote
              run: |
                  git remote add upstream https://github.com/cline/cline.git
                  git fetch upstream --tags

            - name: Create New Branch
              run: |
                  VERSION="${{ needs.check-upstream-releases.outputs.upstream_version }}"
                  BASE_BRANCH="sync-upstream-v${VERSION}"

                  # Find the next available branch suffix
                  COUNTER=1
                  BRANCH="$BASE_BRANCH"
                  while git ls-remote --exit-code origin "refs/heads/$BRANCH" >/dev/null 2>&1; do
                    echo "Branch $BRANCH already exists on remote"
                    BRANCH="${BASE_BRANCH}.${COUNTER}"
                    COUNTER=$((COUNTER + 1))
                  done

                  echo "Using branch name: $BRANCH"
                  echo "branch=$BRANCH" >> $GITHUB_OUTPUT
                  echo "counter=$((COUNTER - 1))" >> $GITHUB_OUTPUT

                  # Create new branch from upstream main
                  git fetch upstream main
                  git checkout -b "$BRANCH" upstream/main

                  # Selectively copy files from main branch
                  echo "Copying files from main branch..."
                  git checkout main -- codemods/

                  echo "Created branch: $BRANCH"

            - name: Apply Codemods
              run: |
                  # Ensure fs-extra is installed for the codemod script
                  npm install fs-extra ts-morph

                  # Apply codemods to clean upstream code
                  node codemods/apply.js

            - name: Install Dependencies
              run: |
                  npm install
                  npm ci
                  npm run format:fix

            - name: Commit Changes
              id: commit
              run: |
                  VERSION="${{ needs.check-upstream-releases.outputs.upstream_version }}"

                  git add .
                  git commit -m "Sync with upstream v${VERSION} and apply codemods"

                  # Push the branch
                  git push -u origin HEAD

                  # Pass through the branch name and counter
                  echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
                  echo "counter=${{ steps.create_new_branch.outputs.counter }}" >> $GITHUB_OUTPUT

    # Run tests on the synced code
    test:
        name: Run Tests
        needs: sync-upstream-release
        uses: ./.github/workflows/test.yml

    # Create a PR for reference (not for merging)
    create-pr:
        name: Create Reference Pull Request
        needs: [sync-upstream-release, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Create Pull Request
              id: create-pr
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ needs.sync-upstream-release.outputs.branch }}
                  base: main
                  title: "[DO NOT MERGE] Reference: Sync with upstream v${{ needs.check-upstream-releases.outputs.upstream_version }}"
                  body: |
                      This PR is for reference only to show the changes from upstream v${{ needs.check-upstream-releases.outputs.upstream_version }}.

                      The changes have been automatically published from the sync branch.
                      DO NOT MERGE THIS PR - it is only for tracking purposes.
                  labels: sync-upstream,do-not-merge

    # Trigger the publish workflow with the sync branch
    publish:
        name: Trigger Publish Workflow
        needs: [sync-upstream-release, test, create-pr]
        runs-on: ubuntu-latest
        steps:
            - name: Trigger publish workflow
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  event-type: auto-publish
                  client-payload: |
                      {
                        "release-type": "release",
                        "branch": "${{ needs.sync-upstream-release.outputs.branch }}",
                        "counter": "${{ needs.sync-upstream-release.outputs.counter }}"
                      }
