name: Sync Upstream Release

on:
    workflow_dispatch:
        inputs:
            tag:
                description: "Upstream tag to sync (e.g., v3.4.8)"
                required: false
                type: string
    schedule:
        # Run every day at midnight UTC
        - cron: "0 0 * * *"

permissions:
    contents: write
    packages: write
    checks: write
    pull-requests: write

jobs:
    check-upstream-releases:
        name: Check for New Upstream Releases
        runs-on: ubuntu-latest
        outputs:
            new_version: ${{ steps.compare_tags.outputs.new_version }}
            upstream_tag: ${{ steps.get_upstream_tag.outputs.upstream_tag }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Get Latest Local Tag
              id: get_local_tag
              run: |
                  LOCAL_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
                  echo "local_tag=$LOCAL_TAG" >> $GITHUB_OUTPUT
                  echo "Latest local tag: $LOCAL_TAG"

            - name: Get Latest Upstream Tag
              id: get_upstream_tag
              run: |
                  # Use provided tag if available
                  if [ -n "${{ github.event.inputs.tag }}" ]; then
                    UPSTREAM_TAG="${{ github.event.inputs.tag }}"
                    echo "Using provided tag: $UPSTREAM_TAG"
                  else
                    # Get latest tag from upstream cline/cline repository
                    UPSTREAM_TAG=$(curl -s https://api.github.com/repos/cline/cline/releases/latest | jq -r .tag_name)

                    if [ -z "$UPSTREAM_TAG" ] || [ "$UPSTREAM_TAG" = "null" ]; then
                      echo "Failed to get latest upstream tag, using GitHub API to get tags"
                      UPSTREAM_TAG=$(curl -s https://api.github.com/repos/cline/cline/tags | jq -r '.[0].name')
                    fi

                    if [ -z "$UPSTREAM_TAG" ] || [ "$UPSTREAM_TAG" = "null" ]; then
                      echo "Failed to get latest upstream tag"
                      exit 1
                    fi
                  fi

                  echo "upstream_tag=$UPSTREAM_TAG" >> $GITHUB_OUTPUT
                  echo "Latest upstream tag: $UPSTREAM_TAG"

            - name: Compare Tags
              id: compare_tags
              run: |
                  LOCAL_TAG=${{ steps.get_local_tag.outputs.local_tag }}
                  UPSTREAM_TAG=${{ steps.get_upstream_tag.outputs.upstream_tag }}

                  # Force sync if manual trigger with tag
                  if [ -n "${{ github.event.inputs.tag }}" ]; then
                    echo "Manual trigger with tag, forcing sync"
                    echo "new_version=true" >> $GITHUB_OUTPUT
                  else
                    # Compare versions
                    if [ "$LOCAL_TAG" != "$UPSTREAM_TAG" ]; then
                      echo "New upstream version detected: $UPSTREAM_TAG (local: $LOCAL_TAG)"
                      echo "new_version=true" >> $GITHUB_OUTPUT
                    else
                      echo "Already on latest version: $LOCAL_TAG"
                      echo "new_version=false" >> $GITHUB_OUTPUT
                    fi
                  fi

    sync-upstream-release:
        name: Sync Upstream Release
        needs: check-upstream-releases
        if: needs.check-upstream-releases.outputs.new_version == 'true' || github.event.inputs.tag != ''
        runs-on: ubuntu-latest
        outputs:
            branch: ${{ steps.commit.outputs.branch }}
            upstream_tag: ${{ needs.check-upstream-releases.outputs.upstream_tag }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.15.1

            - name: Configure Git
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: Add Upstream Remote
              run: |
                  git remote add upstream https://github.com/cline/cline.git
                  git fetch upstream --tags

            - name: Get Tag to Sync
              id: get_tag
              run: |
                  TAG="${{ needs.check-upstream-releases.outputs.upstream_tag }}"
                  echo "tag=$TAG" >> $GITHUB_OUTPUT
                  echo "Syncing tag: $TAG"

            - name: Create New Branch
              run: |
                  TAG=${{ steps.get_tag.outputs.tag }}
                  VERSION=${TAG#v}
                  BRANCH="sync-upstream-$TAG"

                  # Check if branch already exists
                  if git show-ref --verify --quiet "refs/heads/$BRANCH"; then
                    echo "Branch $BRANCH already exists, deleting it"
                    git branch -D "$BRANCH"
                  fi

                  # Create new branch directly from upstream tag without merging main
                  if git show-ref --verify --quiet "refs/tags/$TAG"; then
                    echo "Creating branch from tag $TAG"
                    git checkout -b $BRANCH tags/$TAG
                  elif git show-ref --verify --quiet "refs/remotes/upstream/$TAG"; then
                    echo "Creating branch from upstream/$TAG"
                    git checkout -b "$BRANCH" "upstream/$TAG"
                  else
                    echo "Creating branch from $TAG"
                    git checkout -b "$BRANCH" "$TAG"
                  fi

                  echo "Created branch: $BRANCH"

            - name: Apply Codemods
              run: |
                  # Ensure fs-extra is installed for the codemod script
                  npm install fs-extra ts-morph

                  # Apply codemods to clean upstream code
                  node codemods/apply.js

            - name: Cherry Pick Configuration Changes
              run: |
                  # Get the list of configuration files we want to preserve from main
                  # Add any files that should be preserved from your fork
                  CONFIG_FILES=(
                    ".github/workflows/sync-upstream-release.yml"
                    "codemods/*"
                    # Add other configuration files that should be preserved
                  )

                  # Attempt to cherry pick changes for each config file
                  for file in "${CONFIG_FILES[@]}"; do
                    if git show origin/main:$file > /dev/null 2>&1; then
                      echo "Preserving changes from main for $file"
                      git checkout origin/main -- "$file"
                    fi
                  done

            - name: Install Dependencies
              run: |
                  npm install
                  npm ci
                  npm run format:fix

            - name: Commit Changes
              id: commit
              run: |
                  TAG=${{ steps.get_tag.outputs.tag }}
                  VERSION=${TAG#v}

                  git add .
                  git commit -m "Sync with upstream $TAG and apply codemods"

                  # Push the branch
                  git push -u origin HEAD

                  echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_OUTPUT
                  echo "Changes committed and pushed to branch: $(git rev-parse --abbrev-ref HEAD)"

    # Run tests on the synced code
    test:
        name: Run Tests
        needs: sync-upstream-release
        uses: ./.github/workflows/test.yml

    # Create a PR for reference (not for merging)
    create-pr:
        name: Create Reference Pull Request
        needs: [sync-upstream-release, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Create Pull Request
              id: create-pr
              uses: peter-evans/create-pull-request@v5
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ needs.sync-upstream-release.outputs.branch }}
                  base: main
                  title: "[DO NOT MERGE] Reference: Sync with upstream ${{ needs.sync-upstream-release.outputs.upstream_tag }}"
                  body: |
                      This PR is for reference only to show the changes from upstream ${{ needs.sync-upstream-release.outputs.upstream_tag }}.

                      The changes have been automatically published from the sync branch.
                      DO NOT MERGE THIS PR - it is only for tracking purposes.
                  labels: sync-upstream,do-not-merge

    # Trigger the publish workflow with the sync branch
    publish:
        name: Trigger Publish Workflow
        needs: [sync-upstream-release, test, create-pr]
        runs-on: ubuntu-latest
        steps:
            - name: Trigger publish workflow
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  event-type: auto-publish
                  client-payload: |
                      {
                        "release-type": "release",
                        "branch": "${{ needs.sync-upstream-release.outputs.branch }}"
                      }
